# Generated by Django 5.0.7 on 2024-07-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addre', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
    ]
